config/routes.rb
Idlik12::Application.routes.draw do

  root 'home#index'

  

  resources :donors

  
  resources :gifts
  get 'init_index',         to: 'gifts#init_index',         as: :init_index
  get 'friend',             to: 'gifts#friend',             as: :friend
  get 'select_friend',      to: 'gifts#select_friend',      as: :select_friend
  get 'index_for_friend',   to: 'gifts#index_for_friend',   as: :index_for_friend
  get 'index_for_registry', to: 'gifts#index_for_registry', as: :index_for_registry
  get 'gift_restore_owner', to: 'gifts#give_restore_owner', as: :give_restore_owner
  get 'give_gift',          to: 'gifts#give_gift',          as: :give_gift
  get 'copy_gift',          to: 'gifts#copy_gift',          as: :copy_gift
  

  resource :home
  get 'how',                to: 'home#how',                 as: :how
  get 'what',               to: 'home#what',                as: :what
  get 'faq',                to: 'home#faq',                 as: :faq
  get 'tell',               to: 'home#tell',                as: :tell
  get 'privacy',            to: 'home#privacy',             as: :privacy
  get 'terms',              to: 'home#terms',               as: :terms
  get 'advertise',          to: 'home#advertise',           as: :advertise
  get 'contact',            to: 'home#contact',             as: :contact

  resources :roles,         has_many: :users
  resources :registries
  resources :sources

  resources :user_sessions
  get 'login',              to: 'user_sessions#new',        as: :login
  get "logout",             to: 'user_sessions#destroy',    as: :logout
  get "signup",             to: 'user_sessions#new',        as: :new
  get "orient",             to: 'user_sessions#orient',     as: :orient

  resources :users
  get 'invitation',         to: 'users#invitation',         as: :invitation
  get 'accept_invite',      to: 'users#accept_invite',      as: :accept_invite

  resource :user do
    get 'invite',             to: 'users#invite',             as: :invite
  end

  resources :users do    
    resources :gifts
    resources :registries
  end

  resources :gifts do
    resources :donors
  end

  resources :donors do
    resources :sources
  end

=begin
  get 'registry_toggle'    to: 'gift#registry_toggle,      as: :registry_toggle
  '      { :on => 'change',  :url => { :controller=>'gifts', 
                                  :action => 'registry_toggle', #'registry_toggle', 
                                  :user_id => @user, 
                                  :gift_id => @gift.id,
                                  :registry_id => registry.id },
=end

end

app/views/index.html.haml/_how.erb
<div id="li_body">

<div id="li_content">

<h1 class="no_registries"></h1>

<h3>Once you've joined Idlika, what's next?  Here
	s a reminder!
  <ol>	
    <li>Create a Registry. (At least one is needed before you can display anything you want.)</li><br/>
    <li>Add Gifts (these are images)</li><br/>
      <ul>
	    <li>From your smart phone or tablet</li><br/>
        <li>From any web site</li><br/>
        <li>From your digital camera</li>
      </ul><br/>
    <li>Invite Friends</li><br/>
    <li>Explore and Have Fun!</li>
  </ol>
<br/>
<br/>
</div><!-- li_content -->
<div class="clearer"></div>
</div><!-- li_body -->

app/views/index.html.haml/advertise.erb
<br/><br/>
<h2>Advertise or Sponsor idlika</h2>
<br/><br/>
<br/><br/>
<%= mail_to 'partner@idlika.com' %>

app/views/index.html.haml/careers.erb
<h2>Careers</h2>
<br/>

app/views/index.html.haml/contact_us.erb
<h2>Contact Us</h2>
<br/>
<%= mail_to 'info@idlika.com' %> 

app/views/index.html.haml/faq.erb
<h1>Frequently Asked Questions</h1>

<h3>What is idlika?</h3><p>idlika lets you assemble a gift registry from online links and photos you take yourself!
It was created to allow friends and family to share gift ideas by taking away the stress of not knowing what to buy for that special occasion. idlika allows you to communicating exactly what gifts you’d like to receive. </p>

<h3>How do I add my gift ideas?</h3>
<p>By uploading images you take yourself from your cell phone, digital camera or an image from a web site you can create a gift registry that then through Facebook or email you share your gift ideas with the family and friends you’ve given permission to. 

<h3>Example 1:</h3>
<p>Saw a great pair of shoes in Macy’s and you’d like them for a gift, no problem –Take a photo —log into your idlika account – upload the image into one of your registries you’ve created – write details of the shoes – share with your friends and family. 

<h3>Example 2:</h3>
<p>Have a favorite Spa you’d like to get a gift certificate, no problem – Log into your idlika account – create a gift item - enter the name of the Spa and further information to make it easy for friends and family to get that gift certificate you’d like! From your list, your friends and family can see exactly where and how to get that gift certificate.

<h3>Is idlika free to use?</h3>
<p>idlika is completely free to use. 

<h3>How do I sign up?</h3>
<p>It takes only a minute to sign up for your free idlika account. Before you know it, you’ll be wowed by how easy it is to create and mange your list of gifts.

<h3>Can I tell my friends and family?</h3>
<p>Yes, the whole idea of idlika is to pass on your gift ideas to your friends and family through Facebook Connect or via email—Using your account login access they can go to your list and either click on an item, and purchase the item directly from the retailers website or they can take the information that you’ve provided and go to the retailers store location and purchase the listed gift directly from the retailer.  

<h3>How do I invite my friends with email?</h3>
<p>The best and quickest way is to use your email address book through all the major webmail services (Gmail, Yahoo, AOL, etc.) or import contacts from Outlook. You can also invite your friends on Facebook with one click.

<h3>What is Facebook Connect?</h3>
<p>Facebook Connect allows you to connect your idlika gift registries to your Facebook account.
	Is there a limit on the number of friends and family I can share my gift list with?
	No there is no limit and really the more the better. Not only can they see your gift ideas but we recommend they create their own gift registries and send their list as well to friends and family. 

<h3>How can I share my idlika gift list with friends & family on Facebook?</h3>
<p>Before you can share your idlika gift list with your friends and family on Facebook, you must first connect your idlika account with your Facebook account and log in using Facebook Connect. After that you can share all or just parts of your gift ideas with your Facebook friends and family.

<h3>Will I have the option to remove friends & family from having access to my idlika gift registry?</h3>
<p>Yes, you will have access to not just remove people for your list but add people to your list.

<h3>What is your privacy policy?</h3>
<p>Your privacy is important to us. We do not share your personal information or email address with any third party. We do not sell or give away your information. For more information, please review our <%= link_to 'privacy policy', privacy_path %>.


<h3>Where can I return my items?</h3>
<p>All returns are handled directly from the retailer, so make sure to check the retailer's policies before you make a purchase. 


<h3>Do you have another question?</h3>
<p>If you still need an answer, please send an email to <%= mail_to "info@idlika.com" %>
 and we will try to get back to you right away.

app/views/index.html.haml/how.erb
<div id="li_body">

<div id="li_content">

<h1 class="welcome_to_idlika"></h1>

<h3>Once you've joined Idlika, what's next?  
  <ol>	
    <li>Create a Registry.</li><br/>
    <li>Add Gifts (these are images)</li><br/>
      <ul>
	    <li>From your phone</li><br/>
        <li>From web sites</li><br/>
        <li>From your digital camera</li>
      </ul><br/>
    <li>Invite Friends</li><br/>
    <li>Explore and Have Fun!</li>
  </ol>
<br/>
<br/>
<%= link_to(image_tag("/assets/btn_signup_on.gif", {:alt => 'Start using idlika', :class=>"ta_start"}), new_user_path) %></li>
</div><!-- li_content -->
<div class="clearer"></div>
</div><!-- li_body -->

app/views/index.html.haml/index.html.erb
<!-- shared/header.html.erb -->

<div id="step123">
	
    <div id="step1">
	<% if 1 %>
	  <h1><b>Step 1</b></h1>
	<% else %>
	  <a href="my-idlika.html"><h1><b>Step 1</b></h1>
	<% end %>
    <h2><b>Sign Up</b></h2>
    <p>Whether you're on Facebook, have an iPhone, or just want to sign up online, idlika fits your lifestyle and is easy to take with you, anywhere!</p>
    <img src="assets/step1_stuff.png" alt="Step 1" /></a>
    </div><!-- step1 -->
    
    <div id="step2">
	<% if 1 %>
	  <h1><b>Step 2</b></h1>
    <% else %>
      <a href="my-idlika.html"><h1><b>Step 2</b></h1>
	<% end %>
    <h2><b>Create Your Idlika Registry</b></h2>
    <img src="assets/step2_stuff.png" alt="Step 2" style="float:right; margin:10px 10px 0px 0px;" />
    <p>idlika lets you assemble your personalized registry from online links and photos you take yourself!</p></a>
    </div><!-- step2 -->
    
    <div id="step3">
	<% if 1 %>
      <h1><b>Step 3</b></h1>
	<% else %>
      <a href="my-idlika.html"><h1><b>Step 3</b></h1>
	<% end %>
    <h2><b>Shop Or Share</b></h2>
    <p>Use your registry to streamline your shopping and help remember great items you want — or share it with friends for your birthday, aniversary and more!</p>
    <img src="assets/step3_stuff.png" alt="Step 3" style="margin-top:-15px;" /></a>
    </div><!-- step3 -->

<div class="clearer"></div>
</div><!-- step123 -->
<br/><br/>

<!-- div id="take_action" -->
<% if show_links? %>
  <ul>
	<ui style="float:left;">
	    <%= link_to(image_tag("/assets/btn_getstarted.gif", {:alt => 'Start using idlika', :class=>"ta_start"}), new_user_path) %></li>
	<ui style="float:center;">
		    <%= link_to(image_tag("/assets/btn_howitworks.gif", {:alt => 'How to use idlika', :class=>"ta_how"}), how_path)%></li>
	<ui>
	    <%= link_to(image_tag("/assets/btn_login.gif",  {:alt => 'login to idlika',  :class=>"ta_login"}), new_user_session_path) %></li>
    <br/>
    <ui><iframe src="http://www.facebook.com/widgets/like.php?href=http://www.idlika.com"
        scrolling="no" frameborder="0"
        style="border:none; width:450px; height:80px"></iframe>
    </ui>
    <!-- fb:friendpile></fb:friendpile -->

  </ul>

<!-- % else %>
  <ul><li><a href="login.html" class="ta_login"><b>Log In</b></a></li>
	<li><a href="how-it-works.html" class="ta_how"><b>How It Works</b></a></li>
    <li><a href="get-started.html" class="ta_start"><b>Get Started</b></a></li>
  </ul -->
<% end %>
</div><!-- take_action -->

<!-- shared/footer.html.erb -->

app/views/index.html.haml/privacy.erb
<h2>Privacy Policy</h2>

<p>
	Your privacy is very important to us. Accordingly, we have developed this Policy in order for you to understand how we collect, use, communicate and disclose and make use of personal information. The following outlines our privacy policy.
</p>

<ul>
	<li>
		Before or at the time of collecting personal information, we will identify the purposes for which information is being collected.
	</li>
	<li>
		We will collect and use of personal information solely with the objective of fulfilling those purposes specified by us and for other compatible purposes, unless we obtain the consent of the individual concerned or as required by law.		
	</li>
	<li>
		We will only retain personal information as long as necessary for the fulfillment of those purposes. 
	</li>
	<li>
		We will collect personal information by lawful and fair means and, where appropriate, with the knowledge or consent of the individual concerned. 
	</li>
	<li>
		Personal data should be relevant to the purposes for which it is to be used, and, to the extent necessary for those purposes, should be accurate, complete, and up-to-date. 
	</li>
	<li>
		We will protect personal information by reasonable security safeguards against loss or theft, as well as unauthorized access, disclosure, copying, use or modification.
	</li>
	<li>
		We will make readily available to customers information about our policies and practices relating to the management of personal information. 
	</li>
</ul>

<p>
	We are committed to conducting our business in accordance with these principles in order to ensure that the confidentiality of personal information is protected and maintained. 
</p>		

app/views/index.html.haml/recs_scheds.html.erb
<h2>Records & Schedules</h2>

<p>On-Site Auditor Scheduling
<p>Audit Document/Record Milestones
<p>Auditor Worksheets
<p>Run Report

app/views/index.html.haml/tell.erb
Tell A Friend

app/views/index.html.haml/terms.erb
<h2>
	Web Site Terms and Conditions of Use
</h2>

<h3>
	1. Terms
</h3>

<p>
	By accessing this web site, you are agreeing to be bound by these 
	web site Terms and Conditions of Use, all applicable laws and regulations, 
	and agree that you are responsible for compliance with any applicable local 
	laws. If you do not agree with any of these terms, you are prohibited from 
	using or accessing this site. The materials contained in this web site are 
	protected by applicable copyright and trade mark law.
</p>

<h3>
	2. Use License
</h3>

<ol type="a">
	<li>
		Permission is granted to temporarily download one copy of the materials 
		(information or software) on Idlika, LLC's web site for personal, 
		non-commercial transitory viewing only. This is the grant of a license, 
		not a transfer of title, and under this license you may not:
		
		<ol type="i">
			<li>modify or copy the materials;</li>
			<li>use the materials for any commercial purpose, or for any public display (commercial or non-commercial);</li>
			<li>attempt to decompile or reverse engineer any software contained on Idlika, LLC's web site;</li>
			<li>remove any copyright or other proprietary notations from the materials; or</li>
			<li>transfer the materials to another person or "mirror" the materials on any other server.</li>
		</ol>
	</li>
	<li>
		This license shall automatically terminate if you violate any of these restrictions and may be terminated by Idlika, LLC at any time. Upon terminating your viewing of these materials or upon the termination of this license, you must destroy any downloaded materials in your possession whether in electronic or printed format.
	</li>
</ol>

<h3>
	3. Disclaimer
</h3>

<ol type="a">
	<li>
		The materials on Idlika, LLC's web site are provided "as is". Idlika, LLC makes no warranties, expressed or implied, and hereby disclaims and negates all other warranties, including without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement of intellectual property or other violation of rights. Further, Idlika, LLC does not warrant or make any representations concerning the accuracy, likely results, or reliability of the use of the materials on its Internet web site or otherwise relating to such materials or on any sites linked to this site.
	</li>
</ol>

<h3>
	4. Limitations
</h3>

<p>
	In no event shall Idlika, LLC or its suppliers be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption,) arising out of the use or inability to use the materials on Idlika, LLC's Internet site, even if Idlika, LLC or a Idlika, LLC authorized representative has been notified orally or in writing of the possibility of such damage. Because some jurisdictions do not allow limitations on implied warranties, or limitations of liability for consequential or incidental damages, these limitations may not apply to you.
</p>
		
<h3>
	5. Revisions and Errata
</h3>

<p>
	The materials appearing on Idlika, LLC's web site could include technical, typographical, or photographic errors. Idlika, LLC does not warrant that any of the materials on its web site are accurate, complete, or current. Idlika, LLC may make changes to the materials contained on its web site at any time without notice. Idlika, LLC does not, however, make any commitment to update the materials.
</p>

<h3>
	6. Links
</h3>

<p>
	Idlika, LLC has not reviewed all of the sites linked to its Internet web site and is not responsible for the contents of any such linked site. The inclusion of any link does not imply endorsement by Idlika, LLC of the site. Use of any such linked web site is at the user's own risk.
</p>

<h3>
	7. Site Terms of Use Modifications
</h3>

<p>
	Idlika, LLC may revise these terms of use for its web site at any time without notice. By using this web site you are agreeing to be bound by the then current version of these Terms and Conditions of Use.
</p>

<h3>
	8. Governing Law
</h3>

<p>
	Any claim relating to Idlika, LLC's web site shall be governed by the laws of the State of California without regard to its conflict of law provisions.
</p>

<p>
	General Terms and Conditions applicable to Use of a Web Site.
</p>

app/views/index.html.haml/what.html.erb
<h2>About Idlika</h2>

<h3>idlika gives you the easiest, most convenient and in one place way of sharing “what you want” with your friends and family all on the web.
A simple-to-use solution, idlika enables users to easily share “what I’d like” gift ideas and invite friends & family to view them. </h3>

<p>All it takes is 4 simple steps once you’re logged in.</p>

<ol>
  <li>Create a registry </li>
(Create as many as you like. A registry for your Birthday, going off to College or your Christmas wish list and the registry list goes on)
  <li>Add an image of “what I’d like” from your phone, digital camera or from a web site and upload to the registry</li>
  <li>Fill in the information/description</li>
  <li>Invite friends and family</li>
</ol>

<p>It’s easy, it’s fun and by sharing idlika with your friends and family you’ll see how idlika takes the guessing out of <strong>what to buy</strong> that special someone or what they can buy for YOU!!!</p>

<p>Make life a little easier!!</p>

<br/>
<% if show_links? %>
  <%= link_to 'Create your idlika account', new_user_path %>
  <p/>
  <a href="mailto: info@idlika.com">Start Advertising with Idlika</a>
<% end %>