config/routes.rb
Idlik12::Application.routes.draw do

  root 'home#index'

  

  resources :donors

  
  resources :gifts
  get 'init_index',         to: 'gifts#init_index',         as: :init_index
  get 'friend',             to: 'gifts#friend',             as: :friend
  get 'select_friend',      to: 'gifts#select_friend',      as: :select_friend
  get 'index_for_friend',   to: 'gifts#index_for_friend',   as: :index_for_friend
  get 'index_for_registry', to: 'gifts#index_for_registry', as: :index_for_registry
  get 'gift_restore_owner', to: 'gifts#give_restore_owner', as: :give_restore_owner
  get 'give_gift',          to: 'gifts#give_gift',          as: :give_gift
  get 'copy_gift',          to: 'gifts#copy_gift',          as: :copy_gift
  

  resource :home
  get 'how',                to: 'home#how',                 as: :how
  get 'what',               to: 'home#what',                as: :what
  get 'faq',                to: 'home#faq',                 as: :faq
  get 'tell',               to: 'home#tell',                as: :tell
  get 'privacy',            to: 'home#privacy',             as: :privacy
  get 'terms',              to: 'home#terms',               as: :terms
  get 'advertise',          to: 'home#advertise',           as: :advertise
  get 'contact',            to: 'home#contact',             as: :contact

  resources :roles,         has_many: :users
  resources :registries
  resources :sources

  resources :user_sessions
  get 'login',              to: 'user_sessions#new',        as: :login
  get "logout",             to: 'user_sessions#destroy',    as: :logout
  get "signup",             to: 'user_sessions#new',        as: :new
  get "orient",             to: 'user_sessions#orient',     as: :orient

  resources :users
  get 'invitation',         to: 'users#invitation',         as: :invitation
  get 'accept_invite',      to: 'users#accept_invite',      as: :accept_invite

  resource :user do
    get 'invite',             to: 'users#invite',             as: :invite
  end

  resources :users do    
    resources :gifts
    resources :registries
  end

  resources :gifts do
    resources :donors
  end

  resources :donors do
    resources :sources
  end

=begin
  get 'registry_toggle'    to: 'gift#registry_toggle,      as: :registry_toggle
  '      { :on => 'change',  :url => { :controller=>'gifts', 
                                  :action => 'registry_toggle', #'registry_toggle', 
                                  :user_id => @user, 
                                  :gift_id => @gift.id,
                                  :registry_id => registry.id },
=end

end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic 
    
  has_many :donors 
  has_many :gifts,      :dependent => :destroy
  has_many :registries, :dependent => :destroy
  has_many :roles,      :through => :registries, :source => :user
  has_many :sources,    :dependent => :destroy
  
  serialize :friends
  
  validates_presence_of :name
  validates_presence_of :email
#  validates_acceptance_of :terms_accepted_cb


  def message
    message ||= "message"
  end
      
  def role_symbols
    roles.map do |role|
      role.name.underscore.to_sym
    end
  end
  

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_user, :except => :new
#  before_filter :mailer_set_url_options
  layout 'welcome'
     
  def index
    @users = User.all :order => :name
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = current_user
  end

  def create
    unless params[:user][:terms_accepted_cb]
      flash[:notice] = Constants::TERMS_AND_CONDITIONS
      redirect_to :action => 'new'
    else
      @user = User.new(user_params)
      Role.all.each do |r|
        @user.role_id = r.id if r.name == "guest"
      end
      if @user.save!
        flash[:notice] = Constants::REGISTRATION_SUCCESSFUL 
        UserMailer.welcome_email(@user).deliver
        redirect_to orient_path
      else
         render :action => 'new'
       end
    end
  end

  def update
    @user = current_user
    if @user.update_attributes(params[:user])
      flash[:notice] = Contants::MODIFIED_PROFILE_OK
      redirect_to user_gifts_url(@user)
    else
        render :action => 'edit'
    end
  end
  
  def destroy
    User.destroy params[:id]
    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml  { head :ok }
    end
  end
  
  def invite
    @user = current_user
    @friend = User.new
  end

  # Design Notes
  # It can happen that a user has no friends established (registered on own initiative, for example).
  # For some reason the @invited_friend hash may be nil (actually {nil, nil}).  Skip the update in this case.
  def invitation

    # Person being invited, may be a member already, or not; based on email uniqueness
    if User.exists?(:email => "#{params[:user][:email]}")
      invite_member params
    else
      invite_non_member params
    end
    logger.info "*-*-*-* #{flash[:notice]}"  unless flash[:notice].nil?
    logger.info "*-*-*-* #{flash[:warning]}" unless flash[:warning].nil?
    
    # do not redirect as flash will be lost; provide @user for use in _sidebar.
    # this needs some work as it looks like a partial instead of a render would work.
    @user = current_user
    render :action => :invite
  end
#
# = P R I V A T E = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
#
private

# TEMPORARY -- turned off Thurs pm 7-22 to enable app to run, email may not work
# Turned on Nov 19, 2013 to reactivate as part of idlik12
#  def mailer_set_url_options
#    MemberMailer::Base.default_url_options[:host] = request.host_with_port
#  end

#
# S T R O N G  P A R A M E T E R S
#  
  #attr_accessible :username, :email, :password, :password_confirmation, :terms_accepted_cb
  def user_params
    params.require(:user).permit( :name,
                                  :email,
                                  :password,
                                  :password_confirmation,
                                  :terms_accepted_cb
                                  )
  end
 
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @user, url: {action: "create"}, html: {method: 'post'} do |f| %>

  <div class="aglabelform"><%= f.label :name %>:
  <span class="required">*</span></div>
  <div class="agtext"><%= f.text_field :name %></div>
  <div class="clearer"></div><br/>
  
  <div class="aglabelform"><%= f.label :email %>:
  <span class="required">*</span></div>
  <div class="agtext"><%= f.text_field :email %></div>
  <div class="clearer"></div><br/>

  <div class="aglabelform"><%= f.label :password %>:
  <span class="required">*</span></div>
  <div class="agtext"><%= f.password_field :password %></div>
  <div class="clearer"></div><br/>
  
  <div class="aglabelform"><%= f.label :password %>:
  <span class="required">*</span></div>
  <div class="agtest"><%= f.password_field :password_confirmation %></div>
  <div class="clearer"></div><br/>
 
  <div class="idlikablue">
    <%= f.check_box( :terms_accepted_cb ) %>I have read and accept idlika's 
    <%= link_to 'Terms and Conditions.', terms_path, :target=> 'blank' %>
  </div>
  </p>
<!-- ROLES selection check boxes - probably put these in the admin app
  <p>
    <%= f.label :roles %><br />
    <% for role in Role.all %>
      <%= check_box_tag "user[role_ids][]", role.id, @user.roles.include?(role) %>
      <%=h role.name %> - <%=h role.description %><br />
    <% end %>
  </p>
-->	
  <p><%= image_submit_tag("/assets/btn_signup_on.gif") %></div>

<% end %>

app/views/users/_invitation.html.erb
<%= form_for @friend, url: {action: @user_invitation_path}, html: {class: "addgift_form"} do |f| %>

  <div id="addgift_form">

  <div class="clearer"></div>
  <div class="aglabel" style="width:100px;">Friend's Name:</div>
  <div class="agfield"> <%= f.text_field :name %></div>
  <br />
  
  <div class="clearer"></div>
  <div class="aglabel" style="width:100px;">Friend's Email:</div>
  <div class="agfield"> <%= f.text_field :email %></div>

  <div class="clearer"></div>
  <div class="aglabel" style="width:100px;">Message:</div>
  <%= text_area_tag @user.message %>
  <br />
  <div class="clearer"></div>

 <%= image_submit_tag("/assets/btn_invite_on.gif") %>
</div>

<% end %>

app/views/users/edit.html.erb
<div id="li_body">
<%= render :partial => 'shared/sidebar' %>

<div id="li_content">

<h1 class="my_account"></h1>

  <% form_for @user, url: {action: "edit"}, html: {class: "addgift_form"} do |f| %>

  <div id="addgift_form">

    <div class="clearer"></div>
    <div class="aglabel">Name:</div>
    <div class="agfield"> <%= f.text_field :name, :size=>'60' %></div>
    
    <div class="clearer"></div>
    <div class="aglabel">Email:</div>
    <div class="agfield"> <%= f.text_field :email, :size=>'60' %></div>

    <div class="clearer"></div>
    <div class="aglabel">Password:</div>
    <div class="agfield"> <%= f.password_field :password, :size=>'60' %></div>
 
    <div class="clearer"></div>
    <div class="aglabel">Confirm Password:</div>
    <div class="agfield"> <%= f.password_field :password_confirmation, :size=>'60' %></div>
    <div class="clearer"></div>

  <p><%= image_submit_tag("/assets/btn_submit_on.gif") %></div>

  <% end %>
  </div><!-- addgift_form -->

<!-- link_to 'Back', gifts_path -->

</div><!-- li_content -->

<div class="clearer"></div>
</div><!-- li_body -->

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Username</th>
    <th>Email</th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%=h user.name %></td>
    <td><%=h user.email %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Delete', user_path(user), :confirm => "Are you sure you want to delete #{user.name}?", :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New user', new_user_path %>

app/views/users/invite.html.erb
<div id="li_body">

<%= render 'shared/sidebar' %>

<div id="li_content">
  <h1 class="invite_a_friend"></h1>
  <%= render 'invitation' %>
  <br/>


</div><!-- li_content -->

<div class="clearer"></div>
</div><!-- li_body -->

app/views/users/new.html.erb
<% title 'New User Registration'%>
<div id="li_body">
  <div id="li_content">

  <!-- h1> logon title image here </h1 -->

    <h1 class="recently_added">Join idlika</h1>
    <h1 class="join_idlika"></h1>

      <%= render 'form' %>

<!-- link_to 'Back', gifts_path -->
</div><!-- li_content -->
<div class="clearer"></div>
</div><!-- li_body -->

app/views/users/show.html.erb
<p>
  <b>User name:</b>
  <%=h @user.name %>
</p>

<p>
  <b>Email:</b>
  <%=h @user.email %>
</p>

<p>
  <b>Crypted password:</b>
  <%=h @user.crypted_password %>
</p>

<p>
  <b>Salt:</b>
  <%=h @user.password_salt %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %>
<!-- link_to 'Back', users_path -->