config/routes.rb
Idlik12::Application.routes.draw do

  root 'home#index'

  

  resources :donors

  
  resources :gifts
  get 'init_index',         to: 'gifts#init_index',         as: :init_index
  get 'friend',             to: 'gifts#friend',             as: :friend
  get 'select_friend',      to: 'gifts#select_friend',      as: :select_friend
  get 'index_for_friend',   to: 'gifts#index_for_friend',   as: :index_for_friend
  get 'index_for_registry', to: 'gifts#index_for_registry', as: :index_for_registry
  get 'gift_restore_owner', to: 'gifts#give_restore_owner', as: :give_restore_owner
  get 'give_gift',          to: 'gifts#give_gift',          as: :give_gift
  get 'copy_gift',          to: 'gifts#copy_gift',          as: :copy_gift
  

  resource :home
  get 'how',                to: 'home#how',                 as: :how
  get 'what',               to: 'home#what',                as: :what
  get 'faq',                to: 'home#faq',                 as: :faq
  get 'tell',               to: 'home#tell',                as: :tell
  get 'privacy',            to: 'home#privacy',             as: :privacy
  get 'terms',              to: 'home#terms',               as: :terms
  get 'advertise',          to: 'home#advertise',           as: :advertise
  get 'contact',            to: 'home#contact',             as: :contact

  resources :roles,         has_many: :users
  resources :registries
  resources :sources

  resources :user_sessions
  get 'login',              to: 'user_sessions#new',        as: :login
  get "logout",             to: 'user_sessions#destroy',    as: :logout
  get "signup",             to: 'user_sessions#new',        as: :new
  get "orient",             to: 'user_sessions#orient',     as: :orient

  resources :users
  get 'invitation',         to: 'users#invitation',         as: :invitation
  get 'accept_invite',      to: 'users#accept_invite',      as: :accept_invite

  resource :user do
    get 'invite',             to: 'users#invite',             as: :invite
  end

  resources :users do    
    resources :gifts
    resources :registries
  end

  resources :gifts do
    resources :donors
  end

  resources :donors do
    resources :sources
  end

=begin
  get 'registry_toggle'    to: 'gift#registry_toggle,      as: :registry_toggle
  '      { :on => 'change',  :url => { :controller=>'gifts', 
                                  :action => 'registry_toggle', #'registry_toggle', 
                                  :user_id => @user, 
                                  :gift_id => @gift.id,
                                  :registry_id => registry.id },
=end

end

app/views/shared/_XXregistries.html.erb
<!== rendered from _sidebar partial ==>

<% @user.registries.each do |r| %>
  <% if !r.name.nil? %>
    <li><%= link_to r.name, @user_gift_registry_index_path(@user, r) %></li>
    <li><!= link_to r.name, controller:'gifts', 
                             action:'index_for_registry', 
                             registry_id: r.id 
        !=></li>
    <% if r.name == "#{ENV['DEFAULT_REGISTRY_NAME']}"%>
      <br/>
    <% end %>
  <% end %>
<% end %>

app/views/shared/_XXsidebar.html.erb
	<div id="li_sidebar">
	  <ul>
        <li><%= image_tag "sidenav_myregistries.gif" %></li>
		    <%= render :partial => "shared/registries" %>

        <% if @user.id == current_user[:id] %>
	      <li><%= link_to_unless_current '', new_user_registry_path(@user), :class => "newreg" %>
	      <li><% if @new_registry %>
		        <%= render :partial => 'shared/new_gift_registry' %>
		      <% end %>
		  </li>
	      <li><%= link_to_unless_current '', new_gift_path, :class => "addgift" %></li>
	      <li><%= link_to_unless_current '', user_invite_path(@user), :class => "invitefriend" %></li>
	    <% end %>

	  <% if !@user.friends.nil? %>
        <br/>
        <li>Friends' Registries</li>
        <%= render :partial => "shared/friends", :collection => @user.friends %>
      <% end %>

      </ul>
</div><!-- li_sidebar -->

app/views/shared/_analytics.html.erb
<!-- Start Quantcast tag -->
<script type="text/javascript">
_qoptions={
qacct:"p-13R0YaspdwFro"
};
</script>
<script type="text/javascript" src="http://edge.quantserve.com/quant.js"></script>
<noscript>
<img src="http://pixel.quantserve.com/pixel/p-13R0YaspdwFro.gif" style="display: none;" border="0" height="1" width="1" alt="Quantcast"/>
</noscript>
<!-- End Quantcast tag -->

<!-- Start Google Analytics -->
<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try {
var pageTracker = _gat._getTracker("UA-15539394-1");
pageTracker._trackPageview();
} catch(err) {}</script>
<!-- End Google Analytics -->

app/views/shared/_friend_registries.html.erb
<li><%= link_to 'Recently Added', user_gifts_path(@friend) %></li><br/>

<% @friend.registries.all.each do |@r|%>
  <li><%= link_to @r.name, :controller=>'gifts', :action=>'index_for_registry', 
                           :registry_id=>@r.id unless @r.name = "Recently Added"%></li>
<% end %>

app/views/shared/_friend_sidebar.html.erb
	<div id="li_sidebar">
	  <ul>
	    <li><%= @friend.name %>'s Registries</li>
		<br/>
          <li><!-- link_to 'Recently xAdded', :controller=>'gifts', :action=>'select_friend', :friend_name => @friend.username --></li>

		  <% @friend.registries.all.each do |@r|%>
		    <li><%= link_to @r.name, :controller=>'gifts', 
		                             :action=>'select_friend_registry', 
		                             :id => @friend.id,
		                             :registry_id => @r.id %></li>
		  <% end %>
	  </ul>
	</div><!-- li_sidebar -->

app/views/shared/_friends.html.erb
  <li>
     <%= link_to_unless_current "#{friends[1]}", :controller => 'gifts', :action => 'index_for_friend', :friend_name => "#{friends[1]}"  %>
  </li>		
		

app/views/shared/_header.html.erb
	
<div id="masthead">
	<% if show_links? %>
	   <h1><%= link_to(image_tag("/assets/idlikalogo.gif", 
	                     {:alt => 'Go to my gift registries in idlika'}), root_url ) %></h1>
	  <h2><b>Remember things you want ... Show your friends!</b></h2>
	<% else %>
	  <h1><b>idlika</b></h1></a>
	  <h2><b>Remember things you want ... Show your friends!</b></h2></a>
	<% end %>

<%= render( :partial => '/shared/logon_header')%>

<div class="clearer"></div>

<div id="nav">
  <% if show_links? %>
  <ul>
	<li><%= link_to_unless_current '', root_url, {:class => 'home'} %></li>
    <li><%= link_to_unless_current '', edit_user_path(:current_user), {:class=>'myaccnt'}  %></li>
        <!-- 
       <li> link_to_unless_current "#{@user.name}", {:controller => 'gifts', :action => 'index', :id => @user}, {:class=>'myaccnt'}
       -->


	
  </ul>
  <% end %>
  
</div><!-- nav -->
</div><!-- masthead -->

app/views/shared/_logon_header.html.erb
<div id="loginarea">
  <% if show_links? %>    <!--ENV['RAILS_ENV'] == 'development' % -->
	<div id="user_nav">
		<% if !current_user.nil? %>
		  Hello, <b><%=h current_user[:name] %></b>.  
		  <%= link_to "Logout", logout_path %>
		<% else %>		
		  <%= link_to_unless_current "Register", new_user_path %> |
		  <%= link_to_unless_current "Login", new_user_session_path %>
		<% end %>
	</div>

  <% end %><!-- show_links? ENV['RAILS_ENV'] -->
</div><!-- loginarea -->

app/views/shared/_new_gift_registry.html.erb
<p>Name of the new registry:</p>
<%= text_field_tag( :registry )%>

app/views/shared/_notices.html.erb
<% if !flash[:notice].nil? %>
  <p style="border: 2px solid #009999; 
            padding: 1em;
            margin-bottom: 2em;
            background-color: white;
            font: font-weight: normal/bold; smaller sans-serif; color: #006666 ">
  <%= flash[:notice] %>
  </p>
<% end %>

<% if !flash[:warning].nil? %>
  <p style="border: 2px solid #ffcc00; 
            padding: 1em;
            margin-bottom: 2em;
            background-color: white;
            font: font-weight: normal/bold; smaller sans-serif; color: #006666">
  <%= flash[:warning] %>
  </p>
<% end %>

<% if !flash[:error].nil? %>
  <p style="border: 2px solid red; 
            padding: 1em;
            margin-bottom: 2em;
            background-color: white;
            font: font-weight: normal/bold; smaller sans-serif; color: #006666">
  <%= flash[:error] %>
  </p>
<% end %>

app/views/shared/_registries.html.haml
//rendered from _sidebar partial

- @user.registries.each do |r|

  -if !r.name.nil?
    %li= link_to r.name, controller:'gifts', action:'index_for_registry', registry_id: r.id 
    //%li= link_to r.name, user_registries_path( @user ) 
    - if r.name == "#{ENV['DEFAULT_REGISTRY_NAME']}"
      %br

app/views/shared/_sidebar.html.haml
#li_sidebar

  %ul
    %li= image_tag "sidenav_myregistries.gif"
    =render :partial => "shared/registries"

    - if @user.id == current_user[:id]
      %li= link_to_unless_current '', new_user_registry_path(@user), :class => "newreg"
      -if @new_registry 
        %li= render :partial => 'shared/new_gift_registry'
        %li= link_to_unless_current '', new_gift_path, :class => "addgift"
        %li= link_to_unless_current '', user_invite_path(@user), :class => "invitefriend"

    - if !@user.friends.nil?
      %br
      %li= "Friends' Registries"
      %li= render :partial => "shared/friends", :collection => @user.friends

app/views/shared/_version.html.erb
<div style="font-size:11px; color:#006666; text-align:center;">
  <p><font color='red'><em>Alpha</em></font> -- THIS SITE IS IN ALPHA RELEASE, FEATURES ARE LIMITED, CONTENT MAY NOT BE PRESERVED -- <font color='red'><em>Alpha</em></font></p>
</div>

app/views/shared/_welcome_header.html.erb
	
<div id="masthead">
	<% if show_links? %>
	   <h1><%= link_to(image_tag("/assets/idlikalogo.gif", 
	                     {:alt => 'Go to my gift registries in idlika'}), root_url ) %></h1>
	  <h2><b>Remember things you want ... Show your friends!</b></h2>
	<% else %>
	  <h1><b>idlika</b></h1></a>
	  <h2><b>Remember things you want ... Show your friends!</b></h2></a>
	<% end %>

<%= render( :partial => '/shared/logon_header') %>

<div class="clearer"></div>

</div><!-- masthead -->