config/routes.rb
Idlik12::Application.routes.draw do

  root 'home#index'

  

  resources :donors

  
  resources :gifts
  get 'init_index',         to: 'gifts#init_index',         as: :init_index
  get 'friend',             to: 'gifts#friend',             as: :friend
  get 'select_friend',      to: 'gifts#select_friend',      as: :select_friend
  get 'index_for_friend',   to: 'gifts#index_for_friend',   as: :index_for_friend
  get 'index_for_registry', to: 'gifts#index_for_registry', as: :index_for_registry
  get 'gift_restore_owner', to: 'gifts#give_restore_owner', as: :give_restore_owner
  get 'give_gift',          to: 'gifts#give_gift',          as: :give_gift
  get 'copy_gift',          to: 'gifts#copy_gift',          as: :copy_gift
  

  resource :home
  get 'how',                to: 'home#how',                 as: :how
  get 'what',               to: 'home#what',                as: :what
  get 'faq',                to: 'home#faq',                 as: :faq
  get 'tell',               to: 'home#tell',                as: :tell
  get 'privacy',            to: 'home#privacy',             as: :privacy
  get 'terms',              to: 'home#terms',               as: :terms
  get 'advertise',          to: 'home#advertise',           as: :advertise
  get 'contact',            to: 'home#contact',             as: :contact

  resources :roles,         has_many: :users
  resources :registries
  resources :sources

  resources :user_sessions
  get 'login',              to: 'user_sessions#new',        as: :login
  get "logout",             to: 'user_sessions#destroy',    as: :logout
  get "signup",             to: 'user_sessions#new',        as: :new
  get "orient",             to: 'user_sessions#orient',     as: :orient

  resources :users
  get 'invitation',         to: 'users#invitation',         as: :invitation
  get 'accept_invite',      to: 'users#accept_invite',      as: :accept_invite

  resource :user do
    get 'invite',             to: 'users#invite',             as: :invite
  end

  resources :users do    
    resources :gifts
    resources :registries
  end

  resources :gifts do
    resources :donors
  end

  resources :donors do
    resources :sources
  end

=begin
  get 'registry_toggle'    to: 'gift#registry_toggle,      as: :registry_toggle
  '      { :on => 'change',  :url => { :controller=>'gifts', 
                                  :action => 'registry_toggle', #'registry_toggle', 
                                  :user_id => @user, 
                                  :gift_id => @gift.id,
                                  :registry_id => registry.id },
=end

end

app/models/registry.rb
class Registry < ActiveRecord::Base

  belongs_to :user
  has_many :gifts, :dependent => :destroy
  
  validates_associated :user
#  validates_exclusion_of :name, :in => %w( ENV['DEFAULT_REGISTRY_NAME'] ), :message => "'Recently Added' is reserved. Please choose another name."

#
# D E F A U L T S
#
  after_initialize :defaults

  def defaults
     unless persisted?
    end
  end
    
  
end

app/controllers/registries_controller.rb
class RegistriesController < ApplicationController

  layout 'application'  

  before_filter :require_user 
  before_filter :find_user

  def index
    if session[:current_friend].nil?
      redirect_to user_registry_path(@user, @user.registries )
    else
      redirect_to :controller => 'gifts', :action => 'select_friend', :friend_id => session[:current_friend].id
    end
  end

  # details about a registry
  def show
    @action = session[:current_friend].nil? ? 'index' : 'select_friend'
    respond_to do |format|
      # work out named path at some point
      format.html { redirect_to :controller => 'gifts', :action => "#{@action}",  :registry_id => params[:id] }
      format.xml  { render :xml => @registry }
    end
  end

  # GET /registries/new
  # GET /registries/new.xml 
  def new
    @registry = @user.registries.new

    respond_to do |format|
       format.html  # new.html.erb
       format.xml  { render :xml => @registry }
     end
  end

  # GET /registries/1/edit
  def edit
    @registry = @user.registries.find(params[:id])
  end

  # POST /registries
  # POST /registries.xml
  def create
    @registry = @user.registries.new(registry_params)

    respond_to do |format|
      if @registry.save
        flash[:notice] = 'Registry was successfully created.'
        format.html { redirect_to user_registry_path(@user, @registry) }
        format.xml  { render :xml => @registry, :status => :created, :location => [ @user, @registry] }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @registry.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /registries/1
  # PUT /registries/1.xml
  def update
    @registry = @user.registries.find(params[:id])

    respond_to do |format|
  #    if @registry.update_attributes(params[:registry])
      if @registry.update_attributes(registry_params)
        flash[:notice] = 'Registry was successfully updated.'
        format.html { redirect_to([@user,@registry]) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @registry.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /registries/1
  # DELETE /registries/1.xml
  def destroy
    @registry = Registry.find(params[:id])
    @registry.destroy
    logger.info "*-*-*-*-* #{@registry.name} deleted by #{@user.name}."

    respond_to do |format|
      format.html { redirect_to( user_gifts_url(@user)) }
      format.xml  { head :ok }
    end
  end

  
# + + + + + + + + + + + + + + + + + + + + + + + + + + + + +
private

  def find_user
    @user = current_user
    logger.info "*-*-*-*-* registries_controller.find_user: @user => #{@user.name}, params[:id]=>#{params[:id]}."
  end
  
  # Using a private method to encapsulate the permissible parameters is just a good pattern
  # since you'll be able to reuse the same permit list between create and update. Also, you
  # can specialize this method with per-user checking of permissible attributes.
  def registry_params
    params.require(:registry).permit(:name, :description)
  end

end

app/helpers/registries_helper.rb
module RegistriesHelper
end

app/views/registries/_form.html.erb
<div id="addgift_form">
<div class="clearer"></div>

<div class="aglabel">Registry <%= f.label :name %>:</div>
<div class="agfield" style="width:100px;"><%= f.text_field :name, :class=>"agtext" %></div>
<div class="clearer"></div>

<!-- Peta requested this be removed 
<div class="aglabel">Registry < f.label :description >:</div>
<div class="agfield" style="width:100px;">< f.text_area :description, :class=>"agtext", :size=>'34x3' ></div>
<div class="clearer"></div>
-->

app/views/registries/edit.html.erb
<div id="li_body">
  <%= render :partial => 'shared/sidebar' %>
  <div id="li_content">
  <h1>Edit your registry</h1>
  <!--div id="addgift_form" -->

	<% form_for(@registry) do |f| %>
	  <%= f.error_messages %>

        <%= render :partial => 'form', :locals => { :f => f } %>
	    <%= image_submit_tag("/assets/btn_updateregistry_on.gif") %></div>
	
    <% end %> <!-- form -->

  <!-- addgift_form -->
</div><!-- li_content -->
<br />
<div class="aglabel"></div>
<div class="agfield"><!-- link_to 'Back', user_registries_path(@user) --></div>
<div class="clearer"></div>
</div><!-- li_body --> 

app/views/registries/index.html.erb
<% title 'Registries list'%>
<div id="li_body">
<%= render :partial => 'shared/sidebar' %>

<div id="li_content">
  <h1 class="add_a_gift"><b>Add A Gift</b></h1>

<h1>(Listing registries)</h1>

<table>
  <tr></tr>
  <% @registries.each do |registry| %>
  <tr>
	<td><%=h registry.name %></td>
    <td><%= link_to 'Details', user_registry_path(@user,registry) %> | </td>
    <td><%= link_to 'Edit', edit_user_registry_path(@user,registry) %> | </td>
    <td><%= link_to (image_tag("btn_delete.png"), user_registry_path(@user,registry), 
            :confirm => "Are you sure you want to delete your #{registry.name} registry?  Any gifts still in it will be lost.", 
            :method => :delete )%> </td>
  </tr>
  <% end %>
</table>

<br />
<%= link_to 'New registry', new_user_registry_path(@user) %>
<p></p>
<!-- link_to 'Back', user_gifts_path( @user ) -->

</div><!-- li_content -->

<div class="clearer"></div>
</div><!-- li_body -->

app/views/registries/new.html.erb
<div id="li_body">
<%= render :partial => 'shared/sidebar' %>
<div id="li_content">
  <h1 class="new_registry"></h1>

<%= form_for @registry, url: {action: "create"}, html: {class: "new_registry"} do |f| %>

<div id="addgift_form">
<div class="clearer"></div>

<div class="aglabel">Registry <%= f.label :name %>:</div>
<div class="agfield" style="width:100px;"><%= f.text_field :name, :class=>"agtext" %></div>
<div class="clearer"></div>
  <div class="aglabel"></div>
  <div class="agfield" stylesheet="margin:20px">
	  <%= image_submit_tag("/assets/btn_createregistry_on.gif") %></div>
	</div> <!-- addgift_form -->

<% end %> <!-- form -->

</div><!-- li_content -->
<br />
<div class="aglabel"></div>
<div class="agfield"><!-- link_to 'Back', user_registries_path(@user) --></div>
<div class="clearer"></div>
</div><!-- li_body --> 

 

app/views/registries/show.html.erb
<%= link_to 'Edit', edit_registry_path(@registry) %>
<!-- link_to 'Back', registries_path -->